di_platform_homepage:
    path:     /{_locale}/home
    defaults: { _controller: DIPlatformBundle:Default:index }
    requirements:
        _locale: en|fr

#
#di_platform_signup:
#    path: /signup
#    defaults: { _controller: DIPlatformBundle:Default:signup }
#
di_platform_eshop:
    path: /{_locale}/eshop
    defaults: { _controller: DIPlatformBundle:Default:eshop }
    requirements:
        _locale: en|fr
#
#di_platform_pimp:
#    path: /pimp
#    defaults: { _controller: DIPlatformBundle:Default:pimp }

di_platform_member:
    path: /member
    defaults: { _controller: DIPlatformBundle:Default:member }

di_platform_contact:
    path: /{_locale}/contact
    defaults: { _controller: DIPlatformBundle:Default:contact }
    requirements:
        _locale: en|fr

di_platform_cart:
    path: /{_locale}/cart
    defaults: { _controller: DIPlatformBundle:Default:cart }
    requirements:
        _locale: en|fr

#di_platform_test_product:
#    path: /testprod
#    defaults: { _controller: DIPlatformBundle:Default:testProduct }

di_platform_addtocart:
    path: /addtocart/{id}
    defaults: { _controller: DIPlatformBundle:Default:addtocart }
    requirements:
        id: \d+