<?php

namespace DI\PlatformBundle\Repository;

/**
 * RecettesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecettesRepository extends \Doctrine\ORM\EntityRepository
{
}
